### ISSUE TITLE
MySQL database table creation fails

### ISSUE THREAD

**Issue by pierrei** [mathcamp/pypicloud#74]
When setting up the latest version of pypicloud with MySQL as the caching backend I got this exception:

    Traceback (most recent call last):
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
        return loadobj(APP, uri, name=name, **kw)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
        return context.create()
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
        return self.object_type.invoke(self)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
        return fix_call(context.object, context.global_conf, **context.local_conf)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
        val = callable(*args, **kw)
      File "/opt/pypicloud/virtualenv/src/pypicloud/pypicloud/__init__.py", line 126, in main
        config.include('pypicloud')
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 798, in include
        c(configurator)
      File "/opt/pypicloud/virtualenv/src/pypicloud/pypicloud/__init__.py", line 55, in includeme
        config.include('pypicloud.cache')
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 798, in include
        c(configurator)
      File "/opt/pypicloud/virtualenv/src/pypicloud/pypicloud/cache/__init__.py", line 22, in includeme
        kwargs = cache_impl.configure(settings)
      File "/opt/pypicloud/virtualenv/src/pypicloud/pypicloud/cache/sql.py", line 147, in configure
        create_schema(engine)
      File "/opt/pypicloud/virtualenv/src/pypicloud/pypicloud/cache/sql.py", line 100, in create_schema
        Base.metadata.create_all(bind=engine)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all
        tables=tables)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
        conn._run_visitor(visitorcallable, element, **kwargs)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
        **kwargs).traverse_single(element)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
        return meth(obj, **kw)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 730, in visit_metadata
        _is_metadata_operation=True)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
        return meth(obj, **kw)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 764, in visit_table
        include_foreign_key_constraints=include_foreign_key_constraints
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
        return connection._execute_ddl(self, multiparams, params)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
        compiled
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
        exc_info
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
        self.errorhandler(self, exc, value)
      File "/opt/pypicloud/virtualenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'filename' used in key specification without a key length") [SQL: u'\nCREATE TABLE packages (\n\tfilename TEXT NOT NULL, \n\tname TEXT NOT NULL, \n\tversion TEXT NOT NULL, \n\tlast_modified DATETIME NOT NULL, \n\tdata TEXT NOT NULL, \n\tPRIMARY KEY (filename)\n)\n\n']

This is using SQLAlchemy with the default MySQL engine, but I also got the same error using oursql.

The config I used:

    pypi.db = sql
    db.url = mysql://<username>:<pass>@<amazon-rds-instance-with-mysql-5.5>/pypicloud

Seems like MySQL doesn't support BLOB/TEXT fields as primary key/index key without setting a length:
https://techjourney.net/mysql-error-1170-42000-blobtext-column-used-in-key-specification-without-a-key-length/

**Comment by stevearc** [comment]
Ah, sorry about that. Most of my experience is with Postgres, where you generally just use Text everywhere and it works fine. I've changed the SQL models a bit and it should work with MySQL now. Try verision [0.3.9](https://pypi.python.org/pypi/pypicloud/0.3.9)

**Comment by pierrei** [comment]
Thanks so much man, that did it! :)
