### ISSUE TITLE
passlib ValueError("hash could not be identified")

### ISSUE THREAD

**Issue by zen4ever** [mathcamp/pypicloud#78]
I'm using passwords generated by `ppc-gen-password`
something like `$6$rounds=662480$eD9ewKeo67GHU8KF$bwPiwMy90zjvC5AuN27lBLP5Q3uKZOxX.wswfuVOMG0rntdLqM082XbtKh6UnG.bexmqmftJiGnoZGYy2opEf/` which is a hash for `changeme`

And I'm getting this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/usr/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid_duh/params.py", line 306, in param_twiddler
    return fxn(**scope)
  File "/usr/local/lib/python2.7/site-packages/pypicloud/views/login.py", line 33, in do_login
    if request.access.verify_user(username, password):
  File "/usr/local/lib/python2.7/site-packages/pypicloud/access/base.py", line 230, in verify_user
    return bool(stored_pw and pwd_context.verify(password, stored_pw))
  File "/usr/local/lib/python2.7/site-packages/passlib/context.py", line 2553, in verify
    record = self._get_or_identify_record(hash, scheme, category)
  File "/usr/local/lib/python2.7/site-packages/passlib/context.py", line 2260, in _get_or_identify_record
    return self._identify_record(hash, category)
  File "/usr/local/lib/python2.7/site-packages/passlib/context.py", line 1457, in identify_record
    raise ValueError("hash could not be identified")
```

Any additional configuration I need to specify in my .ini file?

**Comment by stevearc** [comment]
Could you paste the contents of your config file in here? It'll make it much easier to debug/reproduce.

**Comment by zen4ever** [comment]
```
[app:main]
use = egg:pypicloud

pyramid.reload_templates = False
pyramid.debug_authorization = true
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en



pypi.storage = s3
storage.bucket = pypi-production-storage

db.url = sqlite:///%(here)s/db.sqlite

auth.admins =
  admin

user.admin = $6$rounds=662480$eD9ewKeo67GHU8KF$bwPiwMy90zjvC5AuN27lBLP5Q3uKZOxX.wswfuVOMG0rntdLqM082XbtKh6UnG.bexmqmftJiGnoZGYy2opEf/

# For beaker
session.encrypt_key = 2FiTEUOGhBEJKfqcoqx2sxgX0BOCIyLqcMaOkJq9qwM=
session.validate_key = p7By5Md0ET0GP1RSu+byNxoWiqne4CqGVJYlqzFhQKI=
session.secure = false

###
# wsgi server configuration
###

[uwsgi]
paste = config:%p
paste-logger = %p
master = true
processes = 5
reload-mercy = 15
worker-reload-mercy = 15
max-requests = 200
enable-threads = true
http = 0.0.0.0:8000

###
# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root, boto, pypicloud

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_pypicloud]
level = DEBUG
qualname = pypicloud
handlers =

[logger_boto]
level = WARN
qualname = boto
handlers =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)s %(asctime)s [%(name)s] %(message)s
```

**Comment by zen4ever** [comment]
Admin password is `changeme`

**Comment by zen4ever** [comment]
sorry, never mind, I've just discovered that because I run the prod.ini through envsubst to replace environment variables, it replaces "$rounds" with empty string, and it really confuses passlib. Thanks for the quick response

**Comment by stowns** [comment]
> sorry, never mind, I've just discovered that because I run the prod.ini through envsubst to replace environment variables, it replaces "$rounds" with empty string, and it really confuses passlib. Thanks for the quick response

wow...i literally just had the exact same issue and this saved me who knows how much time. thank you @zen4ever
